### ISSUE TITLE
Rotate Video Not Support

### ISSUE THREAD

**Issue by hamid09430** [aws-samples/aws-media-services-simple-vod-workflow#10]
Video Rotate Variable is not working with this convert.py file.

Exception: Parameter validation failed:
Unknown parameter in Settings.Inputs[0].VideoSelector: "Rotate", must be one of: ColorSpace, ColorSpaceUsage, Hdr10Metadata, Pid, ProgramNumber

**Comment by hamid09430** [comment]
please give any hint to fix it

**Comment by aburkleaux-amazon** [comment]
Are you using the pre-packaged lambda function that is created for this lab? It is using an earlier version of boto3 that was created prior to MediaConvert releasing the rotate feature.  

Try using the tutorial to create your own lambda package: https://github.com/aws-samples/aws-media-services-simple-vod-workflow/blob/master/Workflow-WatchfolderAndNotification/README-tutorial.md with the latest version of boto3.

**Comment by stevebanik** [comment]
Does MediaConvert support autorotate with webm inputs?
