### ISSUE TITLE
There was no vod-MediaConverterRole created

### ISSUE THREAD

**Issue by lambo81** [aws-samples/aws-media-services-simple-vod-workflow#32]
"Replace tag in the policy with the ARN for the vod-MediaConvertRole you created earlier."

The vod-MediaConvertRole was not created in a previous step

**Comment by ayacoo** [comment]
@lambo81 I had the same problem. Meant this before: https://github.com/aws-samples/aws-media-services-simple-vod-workflow/tree/master/1-IAMandS3#1-create-an-iam-role-to-use-with-aws-elemental-mediaconvert I just had to realize too that you should start at step 1 for a better understanding :-D

**Comment by seanjackson** [comment]
Good day i am getting i am getting this error message in my cloudwatch log.This is happening when i am doing a batch trancoding.Please kindly help me out i have tried everything nothing is working 
/var/runtime/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'tgzfwmguc.mediaconvert.eu-west-1.amazonaws.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings.

Then my mediaconvert job is showing error  kindly find the attached picture below
![error](https://user-images.githubusercontent.com/11593932/158018307-3be42630-230a-4d24-b0d3-c0796c10917a.png)
