### ISSUE TITLE
Ads not playing

### ISSUE THREAD

**Issue by sambshapiro** [aws-samples/aws-media-services-simple-vod-workflow#4]
Following these instructions exactly produces broken video (not even the content video plays). Tried multiple times with different video players and none work.

Also tried implementing with other test ads, other test content, etc.

While I can successfully get MediaTailor to host a functioning HLS stream without any ads, I cannot get it to serve ads either as pre-roll or elsewhere. Adding #EXT-X-CUE-OUT/IN markers to the playlist file results in broken stream, and the inability for any video players to play even the actual content. 

Similarly, while the documentation states that if these are markers are absent, that MediaTailor will by default serve pre-roll ad based on the ADS response, I cannot replicate this behavior either. If I leave the tags out, the actual content will indeed play, but without any pre-roll.

**Comment by aburkleaux-amazon** [comment]
I ran through the section, 11-VODMediaTailor, using AWS us-east-1 region and Safari to play the HLS video this morning and it was working as expected. i.e. Caminandes video with pre-roll, mid-roll and post-roll.  No manifest manipulation required.

I'm not aware of any outages with dependent AWS services (MediaStore, S3, MediaTailor) this weekend.  

Thanks,
Alex

**Comment by aburkleaux-amazon** [comment]
To help diagnose this you could try to enable logging for MediaTailor: https://docs.aws.amazon.com/mediatailor/latest/ug/monitoring.html

Also, feel free to send (via email) a screen shot of your configuration and your playback link.

- Alex

**Comment by sambshapiro** [comment]
You're right, it's working now; I'm not sure what the issue was on Friday. Seems like it was possibly related to the DoubleClick tags.

I'm now trying to utilize a static VAST tag as the ADS for testing purposes, without VMAP. I've added in the markers to the playlist file, but not seeing any ads. Is there a walkthrough you know of for VOD VAST-only, or VOD ad replacement?

**Comment by morjoan** [comment]
Hi Sam, does your CloudWatch logs show anything to indicate why you're not seeing ads? It would be really helpful for you to turn on monitoring (Alex linked you to instructions).

Meanwhile we have this other tutorial that should do what you want: 
https://github.com/aws-samples/aws-media-services-simple-live-workflow/tree/master/5-MediaTailor
It is for a live workflow, however, if you use your HLS input with ad markers as input (instead of a live origin), and your VAST xml for your ADS then, it should exactly be like what you're looking for.

Some things to keep in mind:
1. make sure your ad markers have EXT-X-CUE-OUT and a corresponding EXT-X-CUE-IN
2. make sure your VAST XML is well-formed (refer to this tutorial https://aws.amazon.com/blogs/media/build-your-own-vast-3-0-response-xml-to-test-with-aws-elemental-mediatailor/)
3. make sure your ad fits well within the ad break duration.  If your ad is longer than the break, you won't see an ad

Good luck!

**Comment by samueleastdev** [comment]
Hi Both,

Thought I might also pitch in on this as I also had issues here is my working playlist.
~~~
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:12
#EXT-X-MEDIA-SEQUENCE:1
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-PROGRAM-DATE-TIME:2018-06-27T05:00:00.166Z
#EXTINF:11,
master720p/00000/master720p_00001.ts
#EXT-X-CUE-OUT:0
#EXT-X-CUE-IN
#EXTINF:12,
master720p/00000/master720p_00002.ts
#EXTINF:11,
master720p/00000/master720p_00003.ts
#EXTINF:11,
master720p/00000/master720p_00004.ts
#EXTINF:11,
master720p/00000/master720p_00005.ts
#EXTINF:12,
master720p/00000/master720p_00006.ts
#EXTINF:11,
master720p/00000/master720p_00007.ts
#EXT-X-CUE-OUT:0
#EXT-X-CUE-IN
#EXTINF:11,
master720p/00000/master720p_00008.ts
#EXTINF:11,
master720p/00000/master720p_00009.ts
#EXTINF:12,
master720p/00000/master720p_00010.ts
#EXTINF:11,
master720p/00001/master720p_00001.ts
#EXTINF:11,
master720p/00001/master720p_00002.ts
#EXTINF:11,
master720p/00001/master720p_00003.ts
#EXTINF:10,
master720p/00001/master720p_00004.ts
#EXT-X-CUE-OUT:0
#EXT-X-CUE-IN
#EXT-X-ENDLIST
~~~

When I first tried it I had a space like this.
~~~
#EXT-X-CUE-OUT: 0
#EXT-X-CUE-IN
~~~

After being on support with AWS they stated to remove the space and it worked.

Also, there seems to be inconsistencies with they way Media Tailor formats their xml and the way Google IMA does.

For instance, this will work in Media Tailor
~~~
<?xml version="1.0" encoding="UTF-8"?>
<vmap:VMAP xmlns:vmap="http://www.iab.net/videosuite/vmap" version="1.0">
 <vmap:AdBreak timeOffset="start" breakType="linear" breakId="preroll">
  <vmap:AdSource id="preroll-ad-1" allowMultipleAds="false" followRedirects="true">
   <vmap:AdTagURI templateType="vast3"><![CDATA[https://pubads.g.doubleclick.net/gampad/ads?slotname=/124319096/external/ad_rule_samples&sz=640x480&ciu_szs=300x250&unviewed_position_start=1&output=xml_vast3&impl=s&env=vp&gdfp_req=1&ad_rule=0&vad_type=linear&vpos=preroll&pod=1&ppos=1&lip=true&min_ad_duration=0&max_ad_duration=30000&vrid=6256&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&url=https://console.aws.amazon.com/support/chat&video_doc_id=short_onecue&cmsid=496&kfa=0&tfcd=0]]></vmap:AdTagURI>
  </vmap:AdSource>
 </vmap:AdBreak>
 <vmap:AdBreak timeOffset="00:00:15.000" breakType="linear" breakId="midroll-1">
  <vmap:AdSource id="midroll-1-ad-1" allowMultipleAds="false" followRedirects="true">
   <vmap:AdTagURI templateType="vast3"><![CDATA[https://pubads.g.doubleclick.net/gampad/ads?slotname=/124319096/external/ad_rule_samples&sz=640x480&ciu_szs=300x250&unviewed_position_start=1&output=xml_vast3&impl=s&env=vp&gdfp_req=1&ad_rule=0&cue=15000&vad_type=linear&vpos=midroll&pod=2&mridx=1&ppos=1&lip=true&min_ad_duration=0&max_ad_duration=30000&vrid=6256&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&url=https://console.aws.amazon.com/support/chat&video_doc_id=short_onecue&cmsid=496&kfa=0&tfcd=0]]></vmap:AdTagURI>
  </vmap:AdSource>
 </vmap:AdBreak>
 <vmap:AdBreak timeOffset="end" breakType="linear" breakId="postroll">
  <vmap:AdSource id="postroll-ad-1" allowMultipleAds="false" followRedirects="true">
   <vmap:AdTagURI templateType="vast3"><![CDATA[https://pubads.g.doubleclick.net/gampad/ads?slotname=/124319096/external/ad_rule_samples&sz=640x480&ciu_szs=300x250&unviewed_position_start=1&output=xml_vast3&impl=s&env=vp&gdfp_req=1&ad_rule=0&vad_type=linear&vpos=postroll&pod=3&ppos=1&lip=true&min_ad_duration=0&max_ad_duration=30000&vrid=6256&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&url=https://console.aws.amazon.com/support/chat&video_doc_id=short_onecue&cmsid=496&kfa=0&tfcd=0]]></vmap:AdTagURI>
  </vmap:AdSource>
 </vmap:AdBreak>
</vmap:VMAP>
~~~
and not here.
https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector

And this will work here: https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector
~~~
<vmap:VMAP xmlns:vmap="http://www.iab.net/videosuite/vmap" version="1.0">
  <vmap:AdBreak timeOffset="start" breakType="linear" breakId="preroll">
    <vmap:AdSource id="preroll-ad" allowMultipleAds="false" followRedirects="true">
      <vmap:AdTagURI templateType="vast3">
        <![CDATA[https://pubads.g.doubleclick.net/gampad/ads?slotname=/124319096/external/ad_rule_samples&sz=640x480&ciu_szs=300x250&unviewed_position_start=1&output=xml_vast3&impl=s&env=vp&gdfp_req=1&ad_rule=0&vad_type=linear&vpos=preroll&pod=1&ppos=1&lip=true&min_ad_duration=0&max_ad_duration=30000&vrid=6256&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&url=https://console.aws.amazon.com/support/chat&video_doc_id=short_onecue&cmsid=496&kfa=0&tfcd=0]]>
      </vmap:AdTagURI>
    </vmap:AdSource>
  </vmap:AdBreak>
  <vmap:AdBreak timeOffset="00:00:5.000" breakType="linear" breakId="midroll">
    <vmap:AdSource id="overlay-1-ad" allowMultipleAds="false" followRedirects="true">
      <vmap:AdTagURI templateType="vast3">
        <![CDATA[https://pubads.g.doubleclick.net/gampad/ads?slotname=/124319096/external/ad_rule_samples&sz=640x480&ciu_szs=300x250&unviewed_position_start=1&output=xml_vast3&impl=s&env=vp&gdfp_req=1&ad_rule=0&cue=15000&vad_type=linear&vpos=midroll&pod=2&mridx=1&ppos=1&lip=true&min_ad_duration=0&max_ad_duration=30000&vrid=6256&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&url=https://console.aws.amazon.com/support/chat&video_doc_id=short_onecue&cmsid=496&kfa=0&tfcd=0]]>
      </vmap:AdTagURI>
    </vmap:AdSource>
  </vmap:AdBreak>
  <vmap:AdBreak timeOffset="end" breakType="linear" breakId="postroll">
    <vmap:AdSource id="postroll-ad" allowMultipleAds="false" followRedirects="true">
      <vmap:AdTagURI templateType="vast3">
        <![CDATA[https://pubads.g.doubleclick.net/gampad/ads?slotname=/124319096/external/ad_rule_samples&sz=640x480&ciu_szs=300x250&unviewed_position_start=1&output=xml_vast3&impl=s&env=vp&gdfp_req=1&ad_rule=0&vad_type=linear&vpos=postroll&pod=3&ppos=1&lip=true&min_ad_duration=0&max_ad_duration=30000&vrid=6256&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&url=https://console.aws.amazon.com/support/chat&video_doc_id=short_onecue&cmsid=496&kfa=0&tfcd=0]]>
      </vmap:AdTagURI>
    </vmap:AdSource>
  </vmap:AdBreak>
</vmap:VMAP>
~~~

But not Media Tailor I am still on support about this.

Which makes it a bit of a pain as you need two separate xml files for the same ad setup one for web and one for Roku etc.
