### ISSUE TITLE
Cloudfront Setup

### ISSUE THREAD

**Issue by samueleastdev** [aws-samples/aws-media-services-simple-vod-workflow#8]
Hi 

If possible could you extend the tutorial to include CloudFront Setup for MediaTailor VOD like on the live workflow example here: https://github.com/aws-samples/aws-media-services-simple-live-workflow/tree/master/5-MediaTailor

Thanks

**Comment by morjoan** [comment]
Added CloudFront integration instructions to MediaTailor.
